### ISSUE TITLE
Move this repository to a new organization

### ISSUE THREAD

**Issue by M5oul** [libre-money-projects/Cuckooland-Project#1]
Would you like to move this repository to [libre money projects organisation](https://github.com/libre-money-projects)?

**Comment by cuckooland** [comment]
Yes, I think it's a very good idea! Do you know the procedure? I found this article:
https://help.github.com/articles/about-repository-transfers/

**Comment by M5oul** [comment]
You can do it on the settings of the repository,
on the bottom, there is a button `Transfer Ownership`.

**Comment by cuckooland** [comment]
Done! Hopefully ...
I let you close this issue?

**Comment by M5oul** [comment]
Nice.
