### ISSUE TITLE
Propositions d’améliorations sur la TRM pour les enfants

### ISSUE THREAD

**Issue by M5oul** [libre-money-projects/Cuckooland-Project#2]
- p2 : GNU **General** Public License
- p31 : nombre **4** n’est pas très reconnaissable
- p40 : la quantité d’euros qui existe**nt** : faute
- p41 : la réserve moyenne a elle aussi doublé**e** : je suis pas sûr de cette proposition
- hommes –> (êtres) humains : p53, 73, 74, 88, 101
- argent (de poche) –> monnaie (de poche) : p66, 76
- 7 ans –> sept ans : p67, 68, 69, 75
- p80 : 10 +1 –> 10 + 1 : manque un espace
- p89 : 2 –> deux
- p90 : 10 DUs –> dix DU
- p90 : on l’a déjà calculé**e** : la monnaie de la bulle précédente
- p92 : 1 pour 40 –> un pour 40
- p93 : 10 –> dix
- p96 : DUs –> DU
- p97, 98 et couverture de dos : La TRM –> la trm : mise en minuscule, typographie
- couverture de dos : argent –> monnaie

**Comment by cuckooland** [comment]
Salut Moul,
Merci pour ces retours !
Je regarde dès mon retour de vacances.
A+
David

Le 12 juin 2016 19:42:05 UTC+02:00, M5oul notifications@github.com a écrit :

> - p2 : GNU **General** Public License
> - p31 : nombre **4** n’est pas très reconnaissable
> - p40 : la quantité d’euros qui existe**nt** : faute
> - p41 : la réserve moyenne a elle aussi doublé**e** : je suis pas sûr
>   de cette proposition
> - hommes –> (êtres) humains : p53, 73, 74, 88, 101
> - argent (de poche) –> monnaie (de poche) : p66, 76
> - 7 ans –> sept ans : p67, 68, 69, 75
> - p80 : 10 +1 –> 10 + 1 : manque un espace
> - p89 : 2 –> deux
> - p90 : 10 DUs –> dix DU
> - p90 : on l’a déjà calculé**e** : la monnaie de la bulle précédente
> - p92 : 1 pour 40 –> un pour 40
> - p93 : 10 –> dix
> - p96 : DUs –> DU
> - p97, 98 et couverture de dos : La TRM –> la trm : mise en minuscule,
>   typographie
> - couverture de dos : argent –> monnaie
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cuckooland/Cuckooland-Project/issues/2

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cuckooland** [comment]
> - p2 : GNU General Public License

En effet, il manquait "General"  

=> **Corrigé**

> - p31 : nombre 4 n’est pas très reconnaissable

Le 4 est en effet très "stylisé", mais en s'appuyant sur le contexte, tu crois que ça peut poser un problème de compréhension ?

=> **Non corrigé**

> - p40 : la quantité d’euros qui existent : faute

Les deux sont possibles, voir :  
[http://www.langue-fr.net/Glossaire#syllepse](http://www.langue-fr.net/Glossaire#syllepse)  

Extrait : "Le choix, par celui qui écrit, de l’une ou l’autre formule permet d’insister davantage sur la notion de foule pris comme un tout... ou celle de multitude (accord avec gens)."

=> **Non corrigé**

> - p41 : la réserve moyenne a elle aussi doublée : je suis pas sûr de cette proposition

Je pense que l'on est dans le cas général où "le participe passé est invariable si le COD est placé après le verbe ou s'il n'y en a pas."  
[http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4221](http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4221)  

=> **Non corrigé**

> - hommes –> (êtres) humains : p53, 73, 74, 88, 101

Avoir un langage non genré (et plus largement non spéciste) est une préoccupation pour moi, mais dans un texte qui ce veut accessible aux enfants, c'est pas simple...

=> **Pas encore corrigé**

> - argent (de poche) –> monnaie (de poche) : p66, 76

Le mot "argent" est un mot piège qu'il faut en effet proscrire, mais il faut surtout expliquer pourquoi ! A la page 73, il y aurait peut-être une occasion :  
"Parfois, certains veulent imposer leurs valeurs, par exemple l’or ou l’argent, comme référentiel, c’est injustifiable et intolérable !"

Ne pas utiliser "argent" avant d'avoir expliquer pourquoi me dérange un peu. "Argent de poche" est une expression, l'idéal serait donc de ne pas l'utiliser, car j'ai peur que "monnaie de poche" ne fasse vraiment pas naturel (ça rejoint le problème du langage non genré : "humain" à la place de "homme" ne fait pas naturel). En même temps, ce coté "non naturel" peut servir à interpeller !

=> **Pas encore corrigé**

> - 7 ans –> sept ans : p67, 68, 69, 75

Pas facile de savoir quand utiliser les chiffres ou les lettres, voir :  
[http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres](http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres)

En résumer : "Dans un souci de clarté et de rapidité, les nombres dans les textes utilitaires s’écriront le plus souvent en chiffres."

=> **Non corrigé**

> - p80 : 10 +1 –> 10 + 1 : manque un espace

En fait, il n'y a aucun espace, ni avant, ni après le "+". Du coup, j'ai joué sur le "kerning" pour corriger ça...  
[http://www.linuxjournal.com/content/scribus-leading-kerning-and-tracking-text](http://www.linuxjournal.com/content/scribus-leading-kerning-and-tracking-text)

Extrait : The combination "Va," for example, leaves a gaping hole between the two characters. Other combinations that may be less than ideal include ff, fi, and fl.

> - p89 : 2 –> deux

En effet, j'ai l'impression (c'est très subjectif) que "deux" à la place de "2" ne nuit pas à la clarté et est plus respectueux de la langue.

=> **corrigé**

> - p90 : 10 DUs –> dix DU

Pour le "10" à remplacer par "dix, retour ici :  
[http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres](http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres)  
On lit : "On écrira les chiffres en cas d’utilisation du symbole de mesure."

=> **Non corrigé**

On lit également : "Les symboles ne s’écrivent pas au pluriel. On écrit 3 kg pas 3 kgs"
Il faut donc remplacer "DUs" par "DU". A la rigueur, on peut vaguement dire que j'ai cédé à un anglicisme :  
[https://fr.wikipedia.org/wiki/Sigle](https://fr.wikipedia.org/wiki/Sigle)

Extrait : "En français, les sigles sont invariables et ne prennent pas la marque du pluriel (contrairement à l'usage anglophone), par exemple : des BD, des HLM, des CD (dont le pluriel en anglais donne CDs)."

=> **Pas encore corrigé** (il y en a beaucoup...)

> - p90 : on l’a déjà calculée : la monnaie de la bulle précédente

J'ai l'impression que l'on est dans un cas particulier, cf. le point 3 (mais aussi 2) ici :  
[http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4221](http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4221)  
Extrait : "Si l' représente une idée exprimée par une proposition ou une phrase, le participe passé est invariable."

=> **Non corrigé**

> - p92 : 1 pour 40 –> un pour 40

Retour ici :  
[http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres](http://www.aproposdecriture.com/ecrire-les-nombres-en-chiffres-ou-en-lettres)  
"Néanmoins, dans une même phrase, deux nombres seront représentés soit en chiffres soit en toutes lettres. Ceci par souci d’uniformité."

=> **Non corrigé**

Par contre, je trouve que le "1" tout seul en fin de ligne est choquant, j'ai modifié ça pour qu'il se retrouve en début de ligne.

> - p93 : 10 –> dix

Il faudrait sans doute "dix" au lieu de "10". Ceci dit, je préférerais plutôt mettre "10 %" au lieu de "10".
En plus, comme les données chiffrées constituent l’objet principal du texte, ce n'est pas choquant ce "10".

=> **Non corrigé**

> - p96 : DUs –> DU

=> **Pas encore corrigé** (il y en a beaucoup...)

> - p97, 98 et couverture de dos : La TRM –> la trm : mise en minuscule, typographie

[https://fr.wikipedia.org/wiki/Sigle](https://fr.wikipedia.org/wiki/Sigle)

"L'usage recommandé au Canada (Guide du rédacteur) et en France (Lexique des règles typographiques en usage à l'Imprimerie nationale) est de typographier les sigles en lettres capitales, sans point d'abréviation. Les acronymes sont typographiés comme des noms propres, avec une majuscule en début de mot (exemples : Unesco, Medef)."

=> **Non corrigé**

**Comment by M5oul** [comment]
> Le 4 est en effet très "stylisé", mais en s'appuyant sur le contexte, tu crois que ça peut poser un problème de compréhension ?

Non, c’est compréhensible, il s’agit uniquement d’une remarque afin que ça puisse être amélioré.

---

Ok, pour les autres points.
